language: bash

branches:
  only:
    - master

before_install:
  - curl --silent https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar xz -C /tmp/

install: true

script: bin/run -c .

env:
  global:
    - SHUNIT_HOME="/tmp/shunit2-2.1.6"
